### ISSUE TITLE
Can't build with react-scripts

### ISSUE THREAD

**Issue by tdaliviu** [nhz-io/react-canvas-component#5]
```
yarn build v0.21.3
$ react-scripts build
Creating an optimized production build...
Failed to compile.

static/js/main.3063e917.js from UglifyJs
SyntaxError: Unexpected token: name (ReactCanvasComponent) [./~/react-canvas-component/dist/react-canvas-component.js:20,0]

error Command failed with exit code 1.
```
Any ideas? I'm using the latest version.

**Comment by nhz-io** [comment]
hmm, this is new for me, gotta check out *react-scripts*

**Comment by nhz-io** [comment]
Well, uglifyjs cannot handle ES6 classes, **react-canvas-component** is distributed as ES6,
I went through https://github.com/firstlookmedia/react-scripts and didnt find any reasonable way to include *react-canvas-component* for **babel-loader**

I could release a patch version and add transpiled to es5 version so uglify wont choke if you like

**Comment by nhz-io** [comment]
Well, i have made a fix to make it work with jshint, but you will have to import the module differently now:
Instead of
```
import Canvas from 'react-canvas-component'
```

You have to explicitly state that you want ES5 transpiled version:
```
import Canvas from 'react-canvas-component/es5'
```js

**Comment by tdaliviu** [comment]
Thanks, the build now passes! 👍 On to testing...
